# Screen:
#     MDBoxLayout:
#         orientation: "vertical"
#         padding: "10dp"
#         spacing: "10dp"

#         MDList:
#             size_hint_y: None
#             height: self.minimum_height

#             OneLineAvatarIconListItem:
#                 text: "Dylan"
#                 on_release: checkbox.active = not checkbox.active

#                 IconLeftWidget:
#                     icon: "account"

#                 MDCheckbox:
#                     id: checkbox
#                     size_hint: None, None
#                     size: "48dp", "48dp"
#                     pos_hint: {"center_y": 0.5}
#                     on_active: app.update_selected("Dylan", self.active)


#         MDRaisedButton:
#             text: "Add Selected"
#             size_hint_y: None
#             height: "48dp"
#             pos_hint: {"center_x": 0.5}
#             on_release: app.add_selected()
